#!/bin/sh
if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root...";
  exit 1;
fi;
export ada0=`zenity --title "Input Query" --entry --text="Enter the name of the storage device to write this operating system to:" --entry-text "ada0"`;
if [ "${ada0}" = "" ]; then
  exit 1;
fi;
`zenity --question --text="This installer script will overwrite '/dev/${ada0}' if such a storage device exists, otherwise the process will fail. Use gpart(8) to list potentially available storage devices to overwrite. This process cannot be undone.\n\nWould you like to install this operating system to your virtual disk?"`;
if [ $? = 0 ]; then
  `zenity --info --text="Please be patient while the operating system is writing files to your virtual disk. Do not log out of this user session or shut down the virtual machine until you have been notified the process is complete."`;
  gpart destroy -F ${ada0};
  gpart create -s gpt ${ada0};
  if [ `sysctl -n machdep.bootmethod` = BIOS ]; then
    gpart add -i 1 -t freebsd-boot -s 512K ${ada0};
    gpart bootcode -i 1 -b /boot/pmbr -p /boot/gptboot ${ada0};
    export x=`diskinfo -v ${ada0} | awk 'FNR==3{print $1}'`;
    export y=`sysctl -n hw.physmem`;
    export z=`echo | awk BEGIN'{print 512*1024}'`
    export s=`echo | awk -v x=$x -v y=$y -v z=$z BEGIN'{print x-y-z}'`;
    gpart add -i 2 -t freebsd-ufs -s $s ${ada0};
    newfs -U -L FreeBSD /dev/${ada0}p2;
    mount /dev/${ada0}p2 /mnt;
    cpdup -i0 -x -vvv / /mnt;
    echo "/dev/${ada0}p2 / ufs rw 1 1" > "/mnt/etc/fstab";
    echo "/dev/${ada0}p3 none swap sw 0 0" >> "/mnt/etc/fstab";
    echo "fdesc /dev/fd fdescfs rw 0 0" >> "/mnt/etc/fstab";
    echo "proc /proc procfs rw 0 0" >> "/mnt/etc/fstab";
    echo "efi_max_resolution=\"1920x1080\"" > "/mnt/boot/loader.conf";
    echo "vbe_max_resolution=\"1920x1080\"" >> "/mnt/boot/loader.conf";
    umount /mnt;
    gpart add -i 3 -t freebsd-swap ${ada0};
    swapon /dev/${ada0}p3;
  else 
    if [ `sysctl -n machdep.bootmethod` = UEFI ]; then
      gpart add -i 1 -t efi -s 40M ${ada0};
      newfs_msdos -F 32 -c 1 /dev/${ada0}p1;
      mount -t msdosfs /dev/${ada0}p1 /mnt;
      mkdir -p /mnt/EFI/BOOT;
      cp /boot/loader.efi /mnt/EFI/BOOT/BOOTX64.efi;
      umount /mnt;
      export x=`diskinfo -v ${ada0} | awk 'FNR==3{print $1}'`;
      export y=`sysctl -n hw.physmem`;
      export z=`echo | awk BEGIN'{print 40*1024*1024}'`
      export s=`echo | awk -v x=$x -v y=$y -v z=$z BEGIN'{print x-y-z}'`;
      gpart add -i 2 -t freebsd-ufs -s $s ${ada0};
      newfs -U -L FreeBSD /dev/${ada0}p2;
      mount /dev/${ada0}p2 /mnt;
      cpdup -i0 -x -vvv / /mnt;
      echo "/dev/${ada0}p2 / ufs rw 1 1" > "/mnt/etc/fstab";
      echo "/dev/${ada0}p3 none swap sw 0 0" >> "/mnt/etc/fstab";
      echo "fdesc /dev/fd fdescfs rw 0 0" >> "/mnt/etc/fstab";
      echo "proc /proc procfs rw 0 0" >> "/mnt/etc/fstab";
      echo "efi_max_resolution=\"1920x1080\"" > "/mnt/boot/loader.conf";
      echo "vbe_max_resolution=\"1920x1080\"" >> "/mnt/boot/loader.conf";
      umount /mnt;
      gpart add -i 3 -t freebsd-swap ${ada0};
      swapon /dev/${ada0}p3;
    fi;
  fi;
  `zenity --info --text="The installation process is now complete! Please shut down the virtual machine and remove the optical disk in order to begin using your virtual disk with persistent storage."`;
fi;
