#!/bin/sh
if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root...";
  exit 1;
fi;
export IMGUI_FONT_SIZE=20;
export IMGUI_DIALOG_FULLSCREEN=1;
export IMGUI_DIALOG_THEME=2;
export IMGUI_TEXT_COLOR_0=1;
export IMGUI_TEXT_COLOR_1=1;
export IMGUI_TEXT_COLOR_2=1;
export IMGUI_HEAD_COLOR_0=0.35;
export IMGUI_HEAD_COLOR_1=0.35;
export IMGUI_HEAD_COLOR_2=0.35;
export IMGUI_AREA_COLOR_0=0.05;
export IMGUI_AREA_COLOR_1=0.05;
export IMGUI_AREA_COLOR_2=0.05;
export IMGUI_BODY_COLOR_0=1;
export IMGUI_BODY_COLOR_1=1;
export IMGUI_BODY_COLOR_2=1;
export IMGUI_POPS_COLOR_0=0.07;
export IMGUI_POPS_COLOR_1=0.07;
export IMGUI_POPS_COLOR_2=0.07;
export gpartshow=`gpart show`;
export def0=`echo ${gpartshow} | awk '{printf $4}'`
export ada0=`/sbin/filedialogs/filedialogs --get-string "${gpartshow}

-----------------------------------------------------------------------

Enter the name of the storage device to write this operating system to:" "${def0}"`;
if [ "${ada0}" = "" ]; then
  exit 1;
fi;
export question=`/sbin/filedialogs/filedialogs --show-question "This installer script will overwrite '/dev/${ada0}' if such a storage device exists, otherwise the process will fail. Use gpart(8) to list potentially available storage devices to overwrite. This process cannot be undone. Would you like to install this operating system to the hard disk?"`;
if [ "${question}" = "Yes" ]; then
  /sbin/filedialogs/filedialogs --show-message "Please be patient while the operating system is writing files to the hard disk. Do not log out of this user session or shut down the machine until you have been notified the process is complete.";
  gpart destroy -F ${ada0};
  gpart create -s gpt ${ada0};
  if [ `sysctl -n machdep.bootmethod` = BIOS ]; then
    gpart add -i 1 -l freebsd-boot -t freebsd-boot -s 512K ${ada0};
    gpart bootcode -b /boot/pmbr -p /boot/gptboot -i 1 ${ada0};
    gpart add -i 2 -l freebsd-root -t freebsd-ufs ${ada0};
    newfs -U /dev/${ada0}p2;
    mount /dev/${ada0}p2 /mnt;
    cpdup -i0 -x -vvv / /mnt;
    echo "/dev/gpt/freebsd-root / ufs rw 1 1" > "/mnt/etc/fstab";
    echo "fdesc /dev/fd fdescfs rw 0 0" >> "/mnt/etc/fstab";
    echo "proc /proc procfs rw 0 0" >> "/mnt/etc/fstab";
    echo "efi_max_resolution=\"1920x1080\"" > "/mnt/boot/loader.conf";
    echo "vbe_max_resolution=\"1920x1080\"" >> "/mnt/boot/loader.conf";
    umount /mnt;
  else 
    if [ `sysctl -n machdep.bootmethod` = UEFI ]; then
      gpart add -i 1 -l freebsd-boot -t efi -s 40M ${ada0};
      gpart add -i 2 -l freebsd-root -t freebsd-ufs ${ada0};
      newfs_msdos -F 32 -c 1 /dev/${ada0}p1;
      mount -t msdosfs /dev/${ada0}p1 /mnt;
      mkdir -p /mnt/EFI/BOOT;
      cp /boot/loader.efi /mnt/EFI/BOOT/BOOTX64.efi;
      umount /mnt;
      newfs -U /dev/${ada0}p2;
      mount /dev/${ada0}p2 /mnt;
      cpdup -i0 -x -vvv / /mnt;
      echo "/dev/gpt/freebsd-root / ufs rw 1 1" > "/mnt/etc/fstab";
      echo "fdesc /dev/fd fdescfs rw 0 0" >> "/mnt/etc/fstab";
      echo "proc /proc procfs rw 0 0" >> "/mnt/etc/fstab";
      echo "efi_max_resolution=\"1920x1080\"" > "/mnt/boot/loader.conf";
      echo "vbe_max_resolution=\"1920x1080\"" >> "/mnt/boot/loader.conf";
      umount /mnt;
    fi;
  fi;
  /sbin/filedialogs/filedialogs --show-message "The installation process is now complete! Please shut down the machine and remove the optical disk in order to begin using the hard disk with persistent storage.";
fi;
